name: Run Scavenger Hunt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  execute_scavenger_hunt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Checksums
        run: |
          echo "f0b3a736d78698c8010bd0e9e98dc4e2fde0961a  javascript/javascript.test.js.gpg" | sha256sum --check --status
          echo "6d92dcf66fc11ca7fc4e66cbecc459f6570d7f00  python/python.test.py.gpg" | sha256sum --check --status
          echo "921af0fab637efe9fe893e96ef679d0374c7b82d  ruby/ruby.test.rb.gpg" | sha256sum --check --status
          echo "e03cd584fbd957fc8eba1960c676d5ce4546b76d  tests/testci.sh.gpg" | sha256sum --check --status

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt
          npm install --prefix javascript
          cd ruby && bundle install && cd ..

      - name: Decrypt tests
        env:
          DECRYPT_SECRET: ${{ secrets.DECRYPT_SECRET }}
        run: |
          if [ -f tests/testci.sh.gpg ]; then
            gpg --batch --yes --passphrase "$DECRYPT_SECRET" -d tests/testci.sh.gpg > tests/testci.sh

            gpg --batch --yes --passphrase "$DECRYPT_SECRET" -d javascript/javascript.test.js.gpg > javascript/javascript.test.js
            gpg --batch --yes --passphrase "$DECRYPT_SECRET" -d python/python.test.py.gpg > python/python.test.py
            gpg --batch --yes --passphrase "$DECRYPT_SECRET" -d ruby/ruby.test.rb.gpg > ruby/ruby.test.rb
            echo "All script files decrypted successfully"
          else
            exit 1
          fi

      - name: Run TestCI
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GITHUB_ACTOR: ${{ vars.GITHUB_ACTOR }}
        run: |
          chmod +x ./tests/testci.sh
          ./tests/testci.sh
